log:
  level: info
  file: "/config/custom-services/mosdns/mosdns.log"

plugins:
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/config/custom-services/geo/geolocation-cn.txt"

  - tag: geosite_noncn
    type: domain_set
    args:
      files:
        - "/config/custom-services/geo/geolocation-!cn.txt"

  - tag: cache
    type: cache
    args:
      size: 8192
      lazy_cache_ttl: 86400

  - tag: forward_smartdns
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "udp://127.0.0.1:5335"
        - addr: "tcp://127.0.0.1:5335"

  - tag: forward_doh
    type: forward
    args:
      upstreams:
        - addr: "https://8.8.8.8/dns-query"

  - tag: main_sequence
    type: sequence
    args:
      - exec: "$cache"
      - matches: "qname $geosite_cn"
        exec: "$forward_smartdns"
      - matches: "qname $geosite_noncn"
        exec: "$forward_doh"
      - exec: "$forward_doh"

servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: "<LAN_BIND_IP>:53"
      - protocol: tcp
        addr: "<LAN_BIND_IP>:53"
